apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dep
  name: dep
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30083
  selector:
    app: dep
  type: NodePort
status:
  loadBalancer: {}
